### ISSUE TITLE
liftover

### ISSUE THREAD

**Issue by TrumanZYX** [pjgreer/ukb-rap-tools#11]
Dear,
  Thanks for your work.
  Thanks for your help.

**Comment by pjgreer** [comment]
If you want to combine imputed data with WES data, I would recommend using the new imputed data field 21007. 
This is imputed against the TOPMED reference panel and is already in GRCH38.

More info on the new data field here:
https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=21007

I have not used it yet, but it should work well.

**Comment by pjgreer** [comment]
You may need to check the UKB RAP for updates.

See here for the TOPMED release:
https://community.dnanexus.com/s/question/0D5t000004DDMDcCAP/new-data-release-genomics-england-and-topmed-imputation-data
and here for some additional tips
https://community.dnanexus.com/s/question/0D5t000004SBxtyCAD/potential-issues-with-imputed-data

see this page for how to update the data:
https://dnanexus.gitbook.io/uk-biobank-rap/getting-started/updating-dispensed-data

You should be able to see the data using the dx ls command:
`dx ls "Bulk/Imputation/Imputation\ from\ genotype\ (TOPmed)/*.bgen"`
