### ISSUE TITLE
Question: Phenotype/Covariate files

### ISSUE THREAD

**Issue by alyssacl** [pjgreer/ukb-rap-tools#5]
Hi Phil,
I appreciate your nice work very much. Thanks for sharing.

Do the phenotype/covariate files have to be the same length as the .sample files?
Or can they be the subsets previously already defined?

Thanks,
Alyssa

**Comment by pjgreer** [comment]
The phenotype and covariate file do not have to be the same size as the .sample file. In all the analyses I have run, I try to use a total sample size of <100k subjects.  

Phil
